name: Build for release

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  windows-release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
      
    - name: Install go-winres
      run: go install github.com/tc-hib/go-winres@latest

    - name: Generate
      run: go generate

    - name: Build
      run: go build
    
    - name: Upload Windows
      uses: actions/upload-artifact@v3
      with:
        name: Windows
        path: ${{github.workspace}}\arf-toolkit.exe
    
    - name: Add Windows to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{github.workspace}}/arf-toolkit.exe